spring:
  application:
    name: snippet-configurations
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:db-configurations}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URI:https://dev-dxazwu1rijz501rx.us.auth0.com/}
          client-id: ${AUTH_CLIENT_ID:client_id}
          client-secret: ${AUTH_CLIENT_SECRET:client_secret}
auth0:
  audience: ${AUTH0_AUDIENCE:https://dev-dxazwu1rijz501rx.us.auth0.com/}
server:
  port: 8082
